# Generated by Django 6.0.7 on 2026-07-19 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TyreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre', models.CharField(max_length=50, verbose_name='TYRE')),
                ('pattern', models.CharField(max_length=80, verbose_name='PATTERN')),
                ('type', models.CharField(max_length=20, verbose_name='TYPE')),
                ('repair_tyre_stock', models.IntegerField(default=0, verbose_name='Repair Tyre Stock')),
                ('rfm_ok_tyre', models.IntegerField(default=0, verbose_name='RFM OK Tyre')),
                ('old_tyres_2025', models.IntegerField(default=0, verbose_name='2025 Old Tyres')),
                ('stock', models.IntegerField(default=0, verbose_name='STOCK')),
                ('on_hold_export', models.IntegerField(default=0, verbose_name='On hold for Export / OR')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tyre', 'pattern', 'type'],
                'unique_together': {('tyre', 'pattern', 'type')},
            },
        ),
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('production', 'Production (Daily Curing)'), ('dispatch', 'Dispatch'), ('adjustment', 'Stock Adjustment')], max_length=15)),
                ('bucket', models.CharField(choices=[('stock', 'STOCK'), ('repair_tyre_stock', 'Repair Tyre Stock'), ('rfm_ok_tyre', 'RFM OK Tyre'), ('old_tyres_2025', '2025 Old Tyres'), ('on_hold_export', 'On hold for Export / OR')], default='stock', max_length=25)),
                ('quantity', models.IntegerField(help_text='Enter positive quantity')),
                ('date', models.DateField()),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to=settings.AUTH_USER_MODEL)),
                ('tyre_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='stock.tyreitem')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
