# Generated by Django 5.2.3 on 2026-07-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_alter_dailyentry_id_alter_tyreitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
