# Generated by Django 5.2.3 on 2026-07-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_dailyentry_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='actual_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Sirf production entries ke liye — is batch ka asli tola hua weight (optional)', max_digits=8, null=True, verbose_name='Actual Weight (KG)'),
        ),
        migrations.AddField(
            model_name='tyreitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ek tyre ka standard/expected weight (KG mein)', max_digits=6, verbose_name='Standard Weight (KG per tyre)'),
        ),
    ]
