# Generated by Django 5.2.3 on 2026-07-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_dailyentry_actual_weight_tyreitem_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyentry',
            name='all_curing',
            field=models.IntegerField(default=0, help_text='Aaj total kitna tyre bana (sab grade milaake)', verbose_name='All Curing'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='lose_tyre',
            field=models.IntegerField(default=0, help_text='Bana lekin abhi pack nahi hua', verbose_name='Lose Tyre'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='production_tyre',
            field=models.IntegerField(default=0, help_text='Pichla/beech mein reh gaya jo aaj complete hua', verbose_name='Production Tyre'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='repair',
            field=models.IntegerField(default=0, help_text='Bana lekin repair mein chala gaya', verbose_name='Repair'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='second_grade',
            field=models.IntegerField(default=0, verbose_name='2nd Grade'),
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='third_grade',
            field=models.IntegerField(default=0, verbose_name='3rd Grade'),
        ),
    ]
