# Generated by Django 5.2.3 on 2026-07-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_dailyentry_all_curing_dailyentry_lose_tyre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProductionManualEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('parchi_kg', models.DecimalField(decimal_places=2, default=0, help_text='Ground se aayi us din ki actual packing weight (parchi)', max_digits=10, verbose_name='Parchi KG')),
                ('mixing_actual_compound', models.DecimalField(decimal_places=2, default=0, help_text='Bahar (mixing section) se aayi actual compound quantity', max_digits=10, verbose_name='Mixing Actual Compound')),
                ('wastage', models.DecimalField(decimal_places=2, default=0, help_text='Us din ki wastage, bahar se manually daali jaati hai', max_digits=10, verbose_name='Wastage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
