# Generated by Django 5.2.3 on 2026-07-29 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='bonus',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='deduction',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'ordering': ['-year']},
        ),
        migrations.AlterModelOptions(
            name='production',
            options={'ordering': ['-date', 'employee']},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('', '---------'), ('CL', 'CL (Casual Leave)'), ('EL', 'EL (Earned Leave)'), ('LOP', 'LOP (Loss of Pay)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hrms.employee'),
        ),
        migrations.AlterField(
            model_name='production',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hrms_productions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='production',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'year')},
        ),
    ]
