# Generated by Django 5.2.3 on 2026-07-30 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access_stock', models.BooleanField(default=False)),
                ('can_access_rawmaterials', models.BooleanField(default=False)),
                ('can_access_cycletube', models.BooleanField(default=False)),
                ('can_access_cycletyres', models.BooleanField(default=False)),
                ('can_access_tallysync', models.BooleanField(default=False)),
                ('can_access_orders', models.BooleanField(default=False)),
                ('can_access_admin_orders', models.BooleanField(default=False)),
                ('can_access_manage_users', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
