# Generated by Django 5.2.3 on 2026-07-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='can_access_admin_orders',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_access_cycletube',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_access_cycletyres',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_access_manage_users',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_access_orders',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_access_rawmaterials',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_access_stock',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='can_access_tallysync',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allowed_pages',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
