# Generated by Django 5.2.3 on 2026-07-22 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallysync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('voucher_date', models.DateField()),
                ('party_name', models.CharField(blank=True, max_length=200)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_synced', models.BooleanField(default=False, help_text='True if all line items matched & stock was reduced')),
                ('raw_payload', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-voucher_date', '-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='TallyItemMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tally_item_name', models.CharField(max_length=150, unique=True)),
                ('module', models.CharField(choices=[('tyre', 'Auto Tyre'), ('tube', 'Cycle Tube'), ('cycletyre', 'Cycle Tyre')], max_length=15)),
                ('item_id', models.PositiveIntegerField(help_text='The ID of the matching item in that module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tally_item_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='tallysynclog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='tallysynclog',
            old_name='received_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tallysynclog',
            old_name='raw_xml',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='tallysynclog',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='tallysynclog',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='tallysynclog',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='tallysynclog',
            name='party_name',
        ),
        migrations.RemoveField(
            model_name='tallysynclog',
            name='processed_at',
        ),
        migrations.RemoveField(
            model_name='tallysynclog',
            name='request_ip',
        ),
        migrations.RemoveField(
            model_name='tallysynclog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='tallysynclog',
            name='voucher_date',
        ),
        migrations.RemoveField(
            model_name='tallysynclog',
            name='voucher_number',
        ),
        migrations.RemoveField(
            model_name='tallysynclog',
            name='voucher_type',
        ),
        migrations.AddField(
            model_name='tallysynclog',
            name='level',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10),
        ),
        migrations.AddField(
            model_name='tallysynclog',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='tallysync.tallyinvoice'),
        ),
    ]
