# Generated by Django 5.2.3 on 2026-07-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallysync', '0002_tallyinvoice_tallyitemmapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyinvoice',
            name='consignee_gstin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tallyinvoice',
            name='consignee_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tallyinvoice',
            name='gst_registration_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tallyinvoice',
            name='party_gstin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tallyinvoice',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tallyinvoice',
            name='state_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
