# Generated by Django 5.2.3 on 2026-07-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallysync', '0003_tallyinvoice_consignee_gstin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallyinvoice',
            name='party_address',
            field=models.TextField(blank=True),
        ),
    ]
