# Generated by Django 5.2.3 on 2026-07-26 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallysync', '0004_tallyinvoice_party_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallySyncSalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True)),
                ('voucher_date', models.DateField()),
                ('party_name', models.CharField(blank=True, max_length=200)),
                ('party_gstin', models.CharField(blank=True, max_length=50)),
                ('party_address', models.TextField(blank=True)),
                ('state_name', models.CharField(blank=True, max_length=100)),
                ('place_of_supply', models.CharField(blank=True, max_length=100)),
                ('gst_registration_type', models.CharField(blank=True, max_length=50)),
                ('consignee_name', models.CharField(blank=True, max_length=200)),
                ('consignee_gstin', models.CharField(blank=True, max_length=50)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock_synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TallySyncSalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('qty', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tallysync.tallysyncsalesinvoice')),
            ],
        ),
    ]
