# Generated by Django 5.2.3 on 2026-07-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tallysync', '0005_tallysyncsalesinvoice_tallysyncsalesitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tallysyncsalesitem',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='TallySyncSalesInvoice',
        ),
        migrations.DeleteModel(
            name='TallySyncSalesItem',
        ),
    ]
