# Generated by Django 5.2.3 on 2026-07-26 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tallysync', '0006_remove_tallysyncsalesitem_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyPendingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tally_item_name', models.CharField(max_length=150)),
                ('qty', models.IntegerField()),
                ('voucher_number', models.CharField(max_length=50)),
                ('voucher_date', models.DateField()),
                ('party_name', models.CharField(blank=True, max_length=200)),
                ('reason', models.CharField(choices=[('unmapped', 'Item Not Mapped'), ('insufficient_stock', 'Insufficient Stock')], max_length=25)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_items', to='tallysync.tallyinvoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
