# Generated by Django 5.2.3 on 2026-07-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawmaterials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['group', 'name']},
        ),
        migrations.AddField(
            model_name='material',
            name='minimum_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.CharField(default='Kg', max_length=20),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='received_by',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='stockentry',
            unique_together={('material', 'date')},
        ),
    ]
