# Generated by Django 5.2.3 on 2026-07-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycletyres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycletyreentry',
            name='all_curing',
            field=models.IntegerField(default=0, verbose_name='All Curing'),
        ),
        migrations.AddField(
            model_name='cycletyreentry',
            name='first_grade',
            field=models.IntegerField(default=0, verbose_name='1st Grade (Black)'),
        ),
        migrations.AddField(
            model_name='cycletyreentry',
            name='rejected_grade',
            field=models.IntegerField(default=0, verbose_name='Rejected Grade'),
        ),
        migrations.AddField(
            model_name='cycletyreentry',
            name='second_grade',
            field=models.IntegerField(default=0, verbose_name='2nd Grade'),
        ),
        migrations.AddField(
            model_name='cycletyreitem',
            name='second_stock',
            field=models.IntegerField(default=0, verbose_name='2nd Grade Stock'),
        ),
        migrations.AddField(
            model_name='cycletyreitem',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0.0, help_text='Weight of tyre in Kg', max_digits=8, verbose_name='Weight (Kg)'),
        ),
        migrations.AlterField(
            model_name='cycletyreentry',
            name='bucket',
            field=models.CharField(choices=[('stock', 'STOCK (1st Grade)'), ('second_stock', '2nd Grade Stock'), ('rfm_stock', 'R.F.M. Stock')], default='stock', max_length=15),
        ),
        migrations.AlterField(
            model_name='cycletyreitem',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='STOCK (1st Grade / Black)'),
        ),
    ]
