# Generated by Django 5.2.3 on 2026-07-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycletyres', '0002_cycletyreentry_all_curing_cycletyreentry_first_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleTyreDailyManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('parchi_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Packing Parch Kg')),
                ('mixing_actual_compound', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mixing Actual Compound')),
                ('chakka', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Chakka')),
                ('calander_bias_cutt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Calander Bias Cutt.')),
                ('packing_wastage', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Packing Wastage')),
                ('tar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tar')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cycle Tyre Daily Manual Entry',
                'verbose_name_plural': 'Cycle Tyre Daily Manual Entries',
                'ordering': ['-date'],
            },
        ),
    ]
