# Generated by Django 5.2.3 on 2026-07-30 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycletube', '0002_cycletubedailymanualentry_and_more'),
        ('cycletyres', '0003_cycletyredailymanualentry'),
        ('orders', '0001_initial'),
        ('stock', '0006_dailyproductionmanualentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='category',
            field=models.CharField(choices=[('auto_tyre', 'Auto Tyre'), ('cycle_tube', 'Cycle Tube'), ('cycle_tyre', 'Cycle Tyre')], default='auto_tyre', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cycle_tyre_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='cycletyres.cycletyreitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='tube_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='cycletube.cycletubeitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dispatched', 'Dispatched'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tyre_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='stock.tyreitem'),
        ),
    ]
