# Generated by Django 5.2.3 on 2026-07-30 03:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycletube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleTubeDailyManualEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('valve_body_issued', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valve Body Issued')),
                ('actual_wt_gross', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Actual wt kgs (Gross)')),
                ('actual_mixing_compound', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Actual Mixing Compound')),
                ('jali', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Jali (Wastage)')),
                ('die_wastage', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Die Wastage')),
                ('tube_cutting', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tube Cutting')),
                ('total_tube_waste', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Tube Waste')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cycle Tube Daily Manual Entry',
                'verbose_name_plural': 'Cycle Tube Daily Manual Entries',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='cycletubeentry',
            name='tube_quality',
            field=models.CharField(choices=[('normal', 'Normal'), ('molded', 'Molded'), ('second', 'Second')], default='normal', help_text='Normal / Molded / Second', max_length=10, verbose_name='Tube Quality'),
        ),
        migrations.AddField(
            model_name='cycletubeitem',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Ek tube ka weight kg mein (e.g. 0.2809)', max_digits=8, verbose_name='Weight (Kg)'),
        ),
    ]
